# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'diabled-disqus'

menu:
#  en: 
# - {uid: 'home', path: 'en', url: 'index.html'}
# - {uid: 'professional-services', path: 'en', url: 'professional-services.html'}
# - {uid: 'industries', path: 'en', url: 'industries.html'}
# - {uid: 'crypto-insights', path: 'en', url: 'crypto-insights.html'}
# - {uid: 'institute-insights', path: 'en', url: 'institute-insights.html'}
# - {uid: 'r-d', path: 'en', url: 'r-d.html'}
# - {uid: 'about-dgi', path: 'en', url: 'about-dgi.html'}
# - {uid: 'contact', path: 'en', url: 'it/contact.html'}
  it:
  - {uid: 'home', path: 'it', url: 'it/index.html'}
  - {uid: 'professional-services', path: 'it', url: 'it/professional-services.html'}
  - {uid: 'industries', path: 'it', url: 'it/industries.html'}
  - {uid: 'crypto-insights', path: 'it', url: 'it/crypto-insights.html'}
  - {uid: 'institute-insights', path: 'it', url: 'it/institute-insights.html'}
  - {uid: 'r-d', path: 'it', url: 'it/r-d.html'}
  - {uid: 'about-dgi', path: 'it', url: 'it/about-dgi.html'}
  - {uid: 'contact', path: 'it', url: 'it/contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {show: true, icon: 'twitter', link: 'https://www.twitter.com/DigitalGoldInst'}
- {show: true, icon: 'facebook-f', link: 'https://www.facebook.com/DigitalGoldInstitute'}
- {show: true, icon: 'linkedin-in', link: 'https://www.linkedin.com/school/digital-gold-institute'}
- {show: true, icon: 'github', link: 'https://www.github.com/dginst'}
- {show: true, icon: 'podcast', link: 'https://dgi.buzzsprout.com/'}
- {show: true, icon: 'rss', link: '/rss-feed.xml'}
- {show: true, icon: 'info', link: '/info'}

info_legal:
    company: Digital Gold Institute S.R.L.
    address: Via Massimo Gorki 47
    region: 20098 San Giuliano Milanese (MI)
    country: ITALY
    piva: 10481200961
    cf: 10481200961
    rea: MI-2534614
    mail: info@dgi.io
    pec: dginst@pec.it
    phone:

info:
    company: Digital Gold Institute S.R.L.
    address: Corso di Porta Romana 61
    region: 20122 Milano (MI)
    country: ITALY
    mail: info@dgi.io
    phone:

