# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'diabled-disqus'

menu:
  en: 
  - {uid: 'home', path: 'en', url: 'index.html'}
  - {uid: 'professional-services', path: 'en', url: 'professional-services.html'}
  - {uid: 'industries', path: 'en', url: 'institutions.html'}
  - {uid: 'r-d', path: 'en', url: 'r-d.html'}
  - {uid: 'crypto-insights', path: 'en', url: 'crypto-insights.html'}
  - {uid: 'about-dgi', path: 'en', url: 'about-dgi.html'}
  - {uid: 'institute-insights', path: 'en', url: 'institute-insights.html'}
  - {uid: 'contact', path: 'en', url: 'contact.html'}
  it:
  - {uid: 'home', path: 'it', url: 'it/index.html'}
  - {uid: 'professional-services', path: 'it', url: 'it/professional-services.html'}
  - {uid: 'industries', path: 'it', url: 'it/industries.html'}
  - {uid: 'r-d', path: 'it', url: 'it/r-d.html'}
  - {uid: 'crypto-insights', path: 'it', url: 'it/crypto-insights.html'}
  - {uid: 'about-dgi', path: 'it', url: 'it/about-dgi.html'}
  - {uid: 'institute-insights', path: 'it', url: 'it/institute-insights.html'}
  - {uid: 'contact', path: 'it', url: 'it/contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {show: true, icon: 'github', link: 'https://'}
- {show: true, icon: 'twitter', link: 'https://'}
- {show: true, icon: 'linkedin', link: 'https:'}

info:
    company: Checksig s.r.l. 
    address: Corso di Porta Romana 61
    region: 20122 Milano (MI)
    country: ITALY
    mail: info@checksig.io
    phone: